### PR TITLE
better logging on case where not saving domain

### PR DESCRIPTION
**Pull request by aeischeid**
mostly better logging. Digging into an issue where mongo domains are not saving as grailsDomainClassMappingContext.getPersistentEntity() returns null for those domains. but this might have helped me see the issue sooner

### CODE REVIEW

**Comment by double16** [comment]
Do you want this merged, or is it a WIP until you solve the domain saving issue?

**Comment by aeischeid** [comment]
No rush, may as well hold off merging for now. We're still working on pinning down the problem. I kind of wanted it noted that mongo is not yet working fully.

**Comment by aeischeid** [comment]
okay at this point would actually be worth merging and functional as a RC4 release that has a semi-functional mongo side to fixtures.

**Comment by double16** [comment]
Published  as RC4

**Pull request merged**
